version: "3.7"
services:
  # POSTGRES SERVER
  pg-docker:
    image: postgres:14-alpine
    container_name: dev-postgresql
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - dev-network
    restart: unless-stopped

  # PGADMIN
  pgadmin-docker:
    image: dpage/pgadmin4
    container_name: dev-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 5050:80
    volumes:
      - pgadmindata:/var/lib/pgadmin
    depends_on:
      - pg-docker
    networks:
      - dev-network
    restart: unless-stopped

# REDE
networks:
  dev-network:
    driver: bridge

# VOLUMES
volumes:
  pgdata:
    driver: local
  pgadmindata:
    driver: local
